// jarvis_data.js — auto-generated by poll_system_stats.py at 2026-08-31T17:37:37
// Static sections (meta title/subtitle, calendar, core, briefButton) are
// carried over from the previous file; live sections (stats, weather,
// connectors, activityLog, bigFigures) reflect only what THIS run actually
// retrieved from the jarvis-dashboard backend at http://127.0.0.1:8002.
window.JARVIS_DATA = {
  "meta": {
    "title": "J.A.R.V.I.S.",
    "subtitle": "Just A Rather Very Intelligent System",
    "dateOverride": null
  },
  "connectors": [
    {
      "name": "HOMELAB BACKEND",
      "status": "online"
    },
    {
      "name": "DOCKER",
      "status": "offline"
    }
  ],
  "activityLog": [
    "[17:24:45] Docker: unavailable \u2014 docker ps failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
    "[17:24:45] Weather: WEATHER_CITY not set server-side \u2014 left unchanged, not guessed",
    "[17:25:36] Homelab poll: load 0.18/8, mem 15.4%, disk 87.4% used",
    "[17:25:36] Docker: unavailable \u2014 docker ps failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
    "[17:25:36] Weather: WEATHER_CITY not set server-side \u2014 showing unavailable, not guessed",
    "[17:37:37] Homelab poll: load 3.09/8, mem 66.1%, disk 88.0% used",
    "[17:37:37] Docker: unavailable \u2014 docker ps failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
    "[17:37:37] Weather: WEATHER_CITY not set server-side \u2014 showing unavailable, not guessed"
  ],
  "stats": [
    {
      "label": "CPU LOAD (1m)",
      "value": 3.09,
      "max": 8,
      "unit": "\u00d7"
    },
    {
      "label": "MEMORY",
      "value": 66.1,
      "max": 100,
      "unit": "%"
    },
    {
      "label": "DISK",
      "value": 61.4,
      "max": 69.7,
      "unit": "GB"
    }
  ],
  "weather": null,
  "calendar": {
    "month": "August",
    "year": 2026,
    "todayDate": 31,
    "firstWeekdayOffset": 6,
    "daysInMonth": 31,
    "events": [
      {
        "day": 31,
        "label": "Jarvis-X: dashboard build"
      },
      {
        "day": 24,
        "label": "Gemini judge decision"
      },
      {
        "day": 13,
        "label": "PWA plan drafted"
      }
    ]
  },
  "bigFigures": [
    {
      "label": "UPTIME",
      "value": "42m"
    },
    {
      "label": "CPU CORES",
      "value": "8"
    },
    {
      "label": "DISK FREE",
      "value": "7.2GB"
    },
    {
      "label": "LAST POLL",
      "value": "17:37:37"
    }
  ],
  "core": {
    "centerLabel": "OK"
  },
  "briefButton": {
    "label": "BRIEF ME",
    "audioSrc": "brief.mp3"
  }
};
