#!/usr/bin/env python3
"""
Polls the jarvis-dashboard backend (cloned from Animesh98/jarvis-dashboard,
running locally at http://127.0.0.1:8002) and rewrites jarvis_data.js's
live-data fields — stats, weather, the relevant connectors, and a few big
figures — from what THIS run actually retrieved. Nothing here is invented:
a failed or skipped call is written as offline/absent, never guessed.

Static fields this script does NOT touch (edit jarvis_data.js by hand for
these, or let the morning-brief skill own them): meta.title/subtitle,
calendar, core, briefButton, and the activityLog lines this script doesn't
itself add.

Run manually, or on a cron/loop, from this directory:
    python3 poll_system_stats.py
"""
import datetime
import json
import subprocess
import sys
import urllib.error
import urllib.request

BACKEND = "http://127.0.0.1:8002"
DATA_JS = "jarvis_data.js"
MAX_LOG_LINES = 8


def fetch(path):
    try:
        with urllib.request.urlopen(f"{BACKEND}{path}", timeout=4) as r:
            return json.loads(r.read().decode()), None
    except (urllib.error.URLError, TimeoutError, ConnectionError) as e:
        return None, str(e)
    except Exception as e:  # malformed JSON, etc — still a real failure, report it
        return None, str(e)


def now_hms():
    return datetime.datetime.now().strftime("%H:%M:%S")


SELF_GENERATED_MARKER = "auto-generated by poll_system_stats.py"


def load_existing():
    """Pull the parts of jarvis_data.js this script leaves alone (meta,
    calendar, core, briefButton) out of the current file, so re-running
    doesn't clobber hand-edited or morning-brief-written content. Falls
    back to sane defaults if the file is missing or unparsable.

    jarvis_data.js is real JS (comments, unquoted keys, trailing commas) —
    not valid JSON/Python-literal syntax, so it's parsed by actually
    running it in node rather than regex-hacking it into something a
    Python parser accepts.

    Also reports whether the file already carries this script's own
    generated-by marker: activityLog entries are only trustworthy to carry
    forward once this script already owns the file — otherwise they're the
    original hand-authored demo lines, which would otherwise persist
    forever alongside real ones with no way to tell them apart."""
    try:
        with open(DATA_JS) as f:
            already_self_generated = SELF_GENERATED_MARKER in f.read()
    except FileNotFoundError:
        already_self_generated = False
    try:
        out = subprocess.run(
            ["node", "-e",
             "globalThis.window = globalThis;"
             f"require('./{DATA_JS}');"
             "console.log(JSON.stringify(window.JARVIS_DATA));"],
            capture_output=True, text=True, timeout=10, check=True,
        )
        data = json.loads(out.stdout)
        if not already_self_generated:
            data["activityLog"] = []  # discard the original hand-authored demo lines
        return data
    except Exception as e:
        print(f"poll_system_stats: could not read existing {DATA_JS} ({e}) — using defaults", file=sys.stderr)
        return {
            "meta": {"title": "J.A.R.V.I.S.", "subtitle": "Just A Rather Very Intelligent System", "dateOverride": None},
            "connectors": [],
            "activityLog": [],
            "calendar": {},
            "core": {"centerLabel": "OK"},
            "briefButton": {"label": "BRIEF ME", "audioSrc": "brief.mp3"},
        }


def main():
    existing = load_existing()

    system, sys_err = fetch("/api/system")
    docker, docker_err = fetch("/api/docker/containers")

    # Replace the connector list entirely rather than merge with whatever was
    # there before: the original file shipped with invented demo entries
    # (LOCAL LLM, SENTINEL, VOICE I/O, CLOUD FALLBACK, BACKUP SYNC) that were
    # never backed by anything real. Keeping those alongside genuinely
    # verified ones would make fabricated status indistinguishable from real
    # status on the same list — so once this poller owns connectors, it only
    # lists what it actually checked this run. (The morning-brief skill owns
    # its own Calendar/Gmail/Notion connectors separately and should follow
    # the same rule when it runs.)
    connectors = [
        {"name": "HOMELAB BACKEND", "status": "online" if system else "offline"},
        {"name": "DOCKER", "status": "online" if docker and "error" not in docker else "offline"},
    ]

    stats = []
    if system:
        load1 = system["cpu_load"][0]
        cores = system["cpu_count"]
        stats.append({"label": "CPU LOAD (1m)", "value": round(load1, 2), "max": cores, "unit": "×"})
        stats.append({"label": "MEMORY", "value": system["memory"]["used_percent"], "max": 100, "unit": "%"})
        stats.append({
            "label": "DISK", "value": system["disk"]["used_gb"], "max": system["disk"]["total_gb"], "unit": "GB",
        })
    else:
        # Keep whatever stats were already there rather than showing an
        # empty panel — but only if this poll couldn't reach the backend.
        stats = existing.get("stats", [])

    big_figures = []
    if system:
        big_figures.append({"label": "UPTIME", "value": system["uptime_human"]})
        big_figures.append({"label": "CPU CORES", "value": str(system["cpu_count"])})
        big_figures.append({"label": "DISK FREE", "value": f'{system["disk"]["free_gb"]}GB'})
    big_figures.append({"label": "LAST POLL", "value": now_hms()})

    log_lines = list(existing.get("activityLog", []))
    if system:
        log_lines.append(
            f'[{now_hms()}] Homelab poll: load {system["cpu_load"][0]}/{system["cpu_count"]}, '
            f'mem {system["memory"]["used_percent"]}%, disk {system["disk"]["used_percent"]}% used'
        )
    else:
        log_lines.append(f"[{now_hms()}] Homelab poll: backend unreachable ({sys_err}) — marked offline")
    if docker_err or (docker and "error" in docker):
        detail = docker.get("error") if docker else docker_err
        log_lines.append(f"[{now_hms()}] Docker: unavailable — {detail}")
    else:
        n = len(docker) if isinstance(docker, list) else "?"
        log_lines.append(f"[{now_hms()}] Docker: {n} container(s) reporting")
    log_lines = log_lines[-MAX_LOG_LINES:]

    # Weather: only include it if a city is actually configured server-side —
    # otherwise wttr.in falls back to IP-geolocating this machine, which is
    # very likely NOT the user's real location. Showing that as "the
    # weather" would be a plausible-looking wrong answer, not an honest gap.
    weather_json, weather_err = fetch("/api/weather")
    # No carry-over here on purpose: a stale or placeholder weather block
    # left in place after this script starts owning the field would look
    # exactly as authoritative as a real one. Once this poller runs, weather
    # is either genuinely fresh or explicitly None — dashboard.html renders
    # None as "WEATHER UNAVAILABLE" rather than a plausible-looking guess.
    weather = None
    if weather_json and "error" not in weather_json and weather_json.get("city"):
        weather = {
            "tempC": weather_json.get("temp_c"),
            "condition": weather_json.get("condition"),
            "humidity": weather_json.get("humidity"),
            "wind": f'{weather_json.get("wind_kph")} km/h {weather_json.get("wind_dir","")}'.strip(),
            "high": None,
            "low": None,
            "tomorrow": None,
        }
    elif weather_json and not weather_json.get("city"):
        log_lines.append(f"[{now_hms()}] Weather: WEATHER_CITY not set server-side — showing unavailable, not guessed")
        log_lines = log_lines[-MAX_LOG_LINES:]
    else:
        log_lines.append(f"[{now_hms()}] Weather: fetch failed ({weather_err}) — showing unavailable")
        log_lines = log_lines[-MAX_LOG_LINES:]

    out = dict(existing)
    out["connectors"] = connectors
    out["stats"] = stats
    out["bigFigures"] = big_figures
    out["activityLog"] = log_lines
    out["weather"] = weather

    js_literal = json.dumps(out, indent=2)
    # json.dumps output is valid JS object literal as-is (no trailing commas,
    # double-quoted keys) — window.JARVIS_DATA accepts it directly.
    content = (
        "// jarvis_data.js — auto-generated by poll_system_stats.py at "
        + datetime.datetime.now().isoformat(timespec="seconds")
        + "\n"
        + "// Static sections (meta title/subtitle, calendar, core, briefButton) are\n"
        + "// carried over from the previous file; live sections (stats, weather,\n"
        + "// connectors, activityLog, bigFigures) reflect only what THIS run actually\n"
        + "// retrieved from the jarvis-dashboard backend at " + BACKEND + ".\n"
        + "window.JARVIS_DATA = " + js_literal + ";\n"
    )
    with open(DATA_JS, "w") as f:
        f.write(content)

    print(f"wrote {DATA_JS}: backend {'online' if system else 'OFFLINE'}, docker {'online' if (docker and 'error' not in docker) else 'OFFLINE'}")


if __name__ == "__main__":
    main()
